### ISSUE TITLE
Chapter 6 - Technical Feedback

### ISSUE THREAD

**Issue by natec425** [destinymalone/head-first-java-cliffsnotes-example#1]
Peer Reviewers: @oscar18guzman, @derekstegall

---

You have some code formatting issues in the snippets in your readme. Be careful about your indentation.

- [x] @oscar18guzman
- [x] @derekstegall

---

Your sample application doesn't demonstrate using `&&` or `||`.

- [x] @oscar18guzman
- [x] @derekstegall

**Comment by destinymalone** [comment]
I believe that I corrected the issue.
